### ISSUE TITLE
When turn ends and someone has a card selected, it is permanently highlighted (but not selected in the backend)

### ISSUE THREAD

**Issue by lilyszhang** [vkoves/codenames-styling#3] opened 2017-11-09 17:31 UTC

**Comment by vkoves** [comment] 2017-11-10 01:10
Actually, I'm not so sure about this being a backend issue. Here's a screenshot of this replicated issue:

![screenshot from 2017-11-09 19-06-12](https://user-images.githubusercontent.com/3187531/32637712-10e9f738-c581-11e7-9ca9-7735a7b105ce.png)

I achieved this by having the blue operator (Doe) choose Organ and end their turn, and then having the red operator (Joe) choose Vacuum and end their turn. Here's two important parts of the last updateBoard call from the backend:

```
Message from server {
    "action": "updateBoard",
    "board": [
...
        [4, {
            "votes": ["Joe"],
            "revealed": false,
            "word": "VACUUM"
        }],
... 
        [4, {
            "votes": ["Doe"],
            "revealed": false,
            "word": "ORGAN"
        }],
...
```

It can be seen that the votes still specify that Joe and Doe have votes in for Vacuum and Organ respectively. The frontend also **completely** redraws the board every time the backend calls `updateBoard` and stores no data in memory about players' selections or even the words that are on the board.

Here's a gist of this server message from the console: https://gist.github.com/vkoves/d4edeae9e7243d997e039b041657ddee

**Comment by vkoves** [comment] 2017-11-19 03:41
I've opened [this back-end issue](https://github.com/nathanshelly/codenames/issues/1) for this, since I have confirmed the front-end is not the cause of the bug. I'm thus closing this issue here.

**Closed as completed by vkoves** 2017-11-19 03:41 UTC
